# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
description: A Helm chart to deploy the oidc-webhook-authenticator application related resources
name: application
version: 0.1.0
